apiVersion: v1
kind: ReplicationController
metadata:
  name: blue-app
  labels:
    app: blue-app
spec:
  replicas: 2
  selector:
    app: blue-app
  template:
    metadata:
      labels:
        app: blue-app
        version: v1.0.0
    spec:
      containers:
      - name: blue-app
        image: hoanggianguet/capstone-docker-image-blue
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: v1.0.0