apiVersion: v1
kind: Service
metadata:
  name: blue-green-service-lb
  labels:
    app: blue-green-service-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80

  # Note here that we match both the app and the version
  selector:
    app: blue-app
    version: v1.0.0